old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
            #use_socket: true
            lazy: true
            prefetch_count: 1
#    consumers:
#        async:
#            connection: default
#            unserializer: json_decode
#            qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
#            lazy: true
#            direct_reply_to: false
#            expect_serialized_response: false
#    rpc_servers:
#        api_request:
#            connection: default
#            callback: 'App\Consumer\ApiRequestConsumer'
#            qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
#            exchange_options: { name: api_request, type: topic }
#            queue_options: { name: api_request_queue, durable: false, auto_delete: true }
#            serializer: json_encode
