security:
    providers:
        app_user_provider:
            entity:
                class: App\Security\Domain\Model\User
                property: username

    password_hashers:
        App\Security\Domain\Model\User:
            algorithm: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            custom_authenticators:
                - App\Security\Infrastructure\Authenticator\LoginFormAuthenticator

            logout:
                path: logout

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register/admin, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED }
