version: "3.4"

services:
  php:
    image: ghcr.io/jameskitt616/orbit_php:main
    restart: unless-stopped
    depends_on:
      - message_transport
    volumes:
      - ./data/php_socket:/var/run/php
      - ./data/live/transcode:/orbit/transcode
      # Set this to the path where to find your video files 
      - /path/to/videos:/orbit/videos
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      #TODO: You should definitely change the password in production
      DATABASE_URL: postgresql://${POSTGRES_USER:-orbit}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-orbit}?serverVersion=${POSTGRES_VERSION:-15}&charset=${POSTGRES_CHARSET:-utf8}

  caddy:
    image: ghcr.io/jameskitt616/orbit_caddy:main
    depends_on:
      - php
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
    restart: unless-stopped
    volumes:
      - ./data/php_socket:/var/run/php
      - ./data/caddy_data:/data
      - ./data/caddy_config:/config
      - ./data/live/transcode:/orbit/transcode
    ports:
      - "80:80"
  
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-orbit}
      #TODO: You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-orbit}
    ports:
      - "5433:5432"
    volumes:
      - ./data/database_data:/var/lib/postgresql/data:rw

  message_transport:
    image: redis:${REDIS_VERSION:-7.0.11}-alpine
    restart: unless-stopped
    volumes:
      - ./data/redis-data:/data
    ports:
      - "6379:6379"
