name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push app_php image
        run: |
          docker buildx build --push -t ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}_php:latest -f Dockerfile .

      - name: Build and push app_caddy image
        run: |
          docker buildx build --push -t ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}_caddy:latest -f Dockerfile --target app_caddy
